version: '3'

services:
  workspace:
    # Override docker image by using a custom build context
    build:
      context: ./containers/custom/workspace

    # Expose additional ports
    ports:
      - 3000:3000
