services:
  selenium_chrome:
    image: chrisnharvey/magiclamp-selenium-chrome:${MAGICLAMP_VERSION:-1.6}

    ports:
      - 4444:4444
      - 4449:5900

    volumes:
      - /dev/shm:/dev/shm

    networks:
      app_net:
        ipv4_address: 10.0.10.30

    dns: 10.0.10.2

    depends_on:
      - dns_internal
