services:
  kafka:
    image: chrisnharvey/magiclamp-kafka:${MAGICLAMP_VERSION:-1.6}

    ports:
      - 9092:9092

    networks:
      app_net:
        ipv4_address: 10.0.10.40

    dns: 10.0.10.2

    depends_on:
      - dns_internal
      - zookeeper

    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper.localhost:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
