services:
  pgadmin:
    image: chrisnharvey/magiclamp-pgadmin:${MAGICLAMP_VERSION:-1.6}

    networks:
      app_net:
        ipv4_address: 10.0.10.16

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-magiclamp@magiclamp.app}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-magicLAMP}"

    dns: 10.0.10.2

    depends_on:
      - dns_internal

volumes:
  pgadmin_data:
