#!/bin/bash

if [ -z $NEW_VERSION ] ; then
    echo "No PHP version specified. Try again with \"NEW_VERSION=7.4 switch-php-version\""
    exit 1
fi

if [ "$EUID" -ne 0 ] ; then
    SUDO="sudo"
fi

if [ -z $ORIGINAL_PATH ] ; then
    export ORIGINAL_PATH=$PATH
fi

COMPOSER_HOME="~/.composer$NEW_VERSION"
PATH="/opt/magicLAMP/php/${NEW_VERSION}:$COMPOSER_HOME/vendor/xbin:/opt/magicLAMP/composer/$NEW_VERSION/vendor/bin":$ORIGINAL_PATH
PHP_PEAR_PHP_BIN="/opt/magicLAMP/php/${NEW_VERSION}/php"

if [ "$SESSION_SWITCH" -eq "1" ]; then
    export COMPOSER_HOME
    export PATH
    export PHP_PEAR_PHP_BIN

    echo "PHP version is set to $NEW_VERSION"
    return 0
elif [ $# -eq 0 ] ; then
    echo "No command specified. To switch version for the current session, run \". $NEW_VERSION\""
    exit 1
fi

COMPOSER_HOME=$COMPOSER_HOME PATH=$PATH PHP_PEAR_PHP_BIN=$PHP_PEAR_PHP_BIN "$@"

exit $?
